---
apiVersion: v1
kind: Pod
metadata:
  name: qbittorrent
spec:
  containers:
    - name: qbittorrent
      image: docker.io/qbittorrentofficial/qbittorrent-nox:4.6.3-1
      env:
        - name: QBT_EULA
          value: accept
        - name: PUID
          value: "0"
        - name: GUID
          value: "0"
      volumeMounts:
        - name: config
          mountPath: /config/qBittorrent
        - name: entrypoint
          mountPath: /entrypoint.sh
        - name: tmpfs
          mountPath: /tmp
        - name: data
          mountPath: /data

    - name: openvpn-client
      image: ghcr.io/wfg/openvpn-client:3.1.0
      securityContext:
        capabilities: {add: ['NET_ADMIN']}
      env:
        - name: VPN_CONFIG_FILE
          value: profile.ovpn
        - name: SUBNETS
          value: "{{ subnet }}"
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: ovpn-profile
          mountPath: /data/vpn/profile.ovpn
          readOnly: true
        - name: dev-net-tun
          mountPath: /dev/net/tun

  volumes:
    - name: config
      hostPath:
        path: /data/.qbittorrent
        type: Directory
    - name: entrypoint
      hostPath:
        path: /opt/qbittorrent/entrypoint.sh
        type: File
    - name: tmpfs
      emptyDir: {}
    - name: data
      hostPath:
        path: /data
        type: Directory

    - name: ovpn-profile
      hostPath:
        path: /etc/vpn/profile.ovpn
        type: File
    - name: dev-net-tun
      hostPath:
        path: /dev/net/tun