---
- name: qBittorrent
  hosts: all
  become: true
  gather_facts: true

  vars:
    netmask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
    subnet: "{{ netmask | ansible.utils.ipaddr('net') }}"

  tasks:
    - name: Check if config dir exists
      ansible.builtin.stat:
        path: /etc/qbittorrent/config
      register: config_dir

    - name: Create directories
      ansible.builtin.file:
        path: /etc/qbittorrent/config
        state: directory
        owner: root
        group: root
        mode: "0755"
      when: not config_dir.stat.exists

    - name: Copy initial config
      ansible.builtin.template:
        src: "{{ item.from }}"
        dest: "{{ item.to  }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - from: default_config.ini
          to: /etc/qbittorrent/config/qBittorrent.conf
      when: not config_dir.stat.exists

    - name: Copy custom entrypoint
      ansible.builtin.template:
        src: "{{ item.from }}"
        dest: "{{ item.to  }}"
        owner: root
        group: root
        mode: "0755"
      loop:
        - from: entrypoint.sh
          to: /etc/qbittorrent/entrypoint.sh

    - name: Copy manifest
      ansible.builtin.template:
        src: "{{ item.from }}"
        dest: "{{ item.to  }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - from: manifest.yaml
          to: /etc/kubernetes/manifests/qbittorrent.yaml
