---
apiVersion: v1
kind: Pod
metadata:
  name: filebrowser
spec:
  containers:
    - name: filebrowser
      image: docker.io/filebrowser/filebrowser:v2.27.0
      args:
        - '--noauth'
      ports:
        - containerPort: 8081
          hostPort: 8081
      livenessProbe:
        httpGet:
          path: /health
          port: 8081
        initialDelaySeconds: 10
        periodSeconds: 3
      volumeMounts:
        - name: config
          mountPath: /.filebrowser.json
        - name: db
          mountPath: /db
        - name: data
          mountPath: /data
  volumes:
    - name: config
      readOnly: true
      hostPath:
        path: /etc/filebrowser/config.json
        type: File
    - name: db
      hostPath:
        path: /opt/filebrowser
        type: Directory
    - name: data
      hostPath:
        path: /data
        type: Directory

