---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus
spec:
  hostNetwork: true
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: prometheus
      image: quay.io/prometheus/prometheus:v2.45.3
      volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          readOnly: true
        - name: data
          mountPath: /prometheus
  volumes:
    - name: config
      hostPath:
        path: /etc/prometheus/prometheus.yml
        type: File
    - name: data
      hostPath:
        path: /data/.prometheus
        type: Directory
