---
apiVersion: v1
kind: Pod
metadata:
  name: grafana
spec:
  hostNetwork: true
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: grafana
      image: docker.io/grafana/grafana-oss:10.3.1
      env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
        - name: GF_AUTH_DISABLE_SIGNOUT_MENU
          value: "true"
      volumeMounts:
        - name: data
          mountPath: /var/lib/grafana
  volumes:
    - name: data
      hostPath:
        path: /data/.grafana
        type: Directory
