---
- name: Jellyfin
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ item  }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      loop:
        - /etc/prometheus
        - /data/.prometheus
        - /data/.grafana

    - name: Copy files
      ansible.builtin.template:
        src: "{{ item.from }}"
        dest: "{{ item.to  }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - from: prometheus.config.yaml
          to: /etc/prometheus/prometheus.yml
        - from: prometheus.yaml
          to: /etc/kubernetes/manifests/prometheus.yaml
        - from: exporters/node-exporter.yaml
          to: /etc/kubernetes/manifests/node-exporter.yaml
        - from: exporters/cadvisor.yaml
          to: /etc/kubernetes/manifests/cadvisor.yaml
        - from: grafana.yaml
          to: /etc/kubernetes/manifests/grafana.yaml
