global:
  scrape_interval: 15s 
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          cluster: nas-pi
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:9092']
        labels:
          cluster: nas-pi
          node: nas-pi
