---
- name: Restart containerd service
  ansible.builtin.systemd_service:
    name: containerd
    daemon_reload: true
    state: restarted
  listen: containerd_restart
  notify: kubelet_restart

- name: Restart kubelet.service
  ansible.builtin.systemd_service:
    name: kubelet
    daemon_reload: true
    state: restarted
  listen: kubelet_restart
