---
apiVersion: v1
kind: Pod
metadata:
  name: carvisor
spec:
  hostNetwork: true
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: carvisor
      image: gcr.io/cadvisor/cadvisor:v0.47.2
      args: 
        - '-port=9092'
        - '-containerd=/rootfs/run/containerd/containerd.sock'
      volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: run
          mountPath: /var/run
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: disk
          mountPath: /dev/disk
          readOnly: true
  volumes:
    - name: rootfs
      hostPath:
        path: /
    - name: run
      hostPath:
        path: /var/run
    - name: sys
      hostPath:
        path: /sys
    - name: disk
      hostPath:
        path: /dev/disk
