---
apiVersion: v1
kind: Pod
metadata:
  name: carvisor
spec:
  hostNetwork: true
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: carvisor
      image: gcr.io/cadvisor/cadvisor:v0.47.2
      args: ['-port=9092']
      volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
  volumes:
    - name: rootfs
      hostPath:
        path: /
