---
apiVersion: v1
kind: Pod
metadata:
  name: node-exporter
spec:
  hostNetwork: true
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: node-exporter
      image: quay.io/prometheus/node-exporter:v1.7.0
      volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: run
          mountPath: /var/run
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: disk
          mountPath: /dev/disk
          readOnly: true
  volumes:
    - name: rootfs
      hostPath:
        path: /
    - name: run
      hostPath:
        path: /var/run
    - name: sys
      hostPath:
        path: /sys
    - name: disk
      hostPath:
        path: /dev/disk
