---
apiVersion: v1
kind: Pod
metadata:
  name: jellyfin
spec:
  containers:
    - name: jellyfin
      image: docker.io/jellyfin/jellyfin:10.8.13
      ports:
        - containerPort: 8096
          hostPort: 8096
      volumeMounts:
        - name: config
          mountPath: /config
        - name: cache
          mountPath: /cache
        - name: media
          mountPath: /media
          readOnly: true
  volumes:
    - name: config
      hostPath:
        path: /data/.jellyfin/config
        type: Directory
    - name: cache
      hostPath:
        path: /data/.jellyfin/cache
        type: Directory
    - name: media
      hostPath:
        path: /data/media
        type: Directory
