---
apiVersion: v1
kind: Pod
metadata:
  name: node-exporter
spec:
  hostNetwork: true
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: node-exporter
      image: quay.io/prometheus/node-exporter:v1.7.0
      args: ['--path.rootfs=/host']
      ports:
        - containerPort: 9100
          hostPort: 9100
      volumeMounts:
        - name: rootfs
          mountPath: /host
          readOnly: true
  volumes:
    - name: rootfs
      hostPath:
        path: /
      readOnly: true
